#!/usr/bin/bash
# cosmic-net-box — create and maintain the rootful `net` distrobox (spec N4, N5, C1c).
# Run by cosmic-net-box.service at boot (retries until the network is up) and after
# every image update; idempotent, so a run with nothing to do changes nothing.
#
#   1. create the box from /usr/share/fedora-cosmic-atomic/net-box.ini if it is missing
#   2. install every vendor .deb in /var/lib/net-box/installers/ that is not installed yet
#   3. menu launchers for the vendor apps found in the box (/usr/local/share/applications)
#   4. root-owned wrappers in /usr/local/bin for the network tools (nmap, mtr, tcpdump)
set -euo pipefail
INI=/usr/share/fedora-cosmic-atomic/net-box.ini
BOX=net
STATE=/var/lib/net-box
APPS=/usr/local/share/applications
BIN=/usr/local/bin

install -d -m 0755 "$STATE/installers" "$STATE/cisco-profile" "$APPS" "$BIN"

if ! podman container exists "$BOX"; then
    echo "creating the $BOX box from $INI"
    distrobox assemble create --file "$INI"
fi
podman start "$BOX" >/dev/null

# Vendor packages: install what is in the folder and not yet in the box.
shopt -s nullglob
for deb in "$STATE"/installers/*.deb; do
    pkg=$(podman exec "$BOX" dpkg-deb -f "/installers/$(basename "$deb")" Package)
    if podman exec "$BOX" dpkg-query -W -f '${Status}' "$pkg" 2>/dev/null | grep -q "install ok installed"; then
        continue
    fi
    echo "installing $pkg from $(basename "$deb")"
    podman exec -e DEBIAN_FRONTEND=noninteractive "$BOX" apt-get install -y -q "/installers/$(basename "$deb")"
done

# Launchers for the vendor GUIs that are present. A rootful box needs sudo, so they open
# in a terminal that asks for the password once.
launcher() {  # id, name, command inside the box
    local id="$1" name="$2" cmd="$3"; local f="$APPS/net-box-$id.desktop"
    if podman exec "$BOX" test -x "${cmd%% *}"; then
        cat > "$f" <<EOT
[Desktop Entry]
Type=Application
Name=$name (net box)
Exec=distrobox enter --root $BOX -- $cmd
Terminal=true
Icon=network-vpn
Categories=Network;
EOT
        chmod 0644 "$f"
    else
        rm -f "$f"
    fi
}
launcher cisco "Cisco Secure Client" "/opt/cisco/secureclient/bin/vpnui"
launcher windscribe "Windscribe" "/opt/windscribe/Windscribe"

# Network tools that need real root: run them in the box (sudo asks once).
for tool in nmap mtr tcpdump; do
    cat > "$BIN/$tool" <<EOT
#!/bin/sh
# Generated by cosmic-net-box: $tool runs as root in the rootful net box (spec C1c).
if [ -t 0 ]; then t=-it; else t=-i; fi
exec sudo podman exec \$t $BOX $tool "\$@"
EOT
    chmod 0755 "$BIN/$tool"
done
echo "net box ready"
