#!/usr/bin/env bash
# enable-vfio.sh — DESKTOP: hand the 2TB NVMe controller to vfio-pci for the
# Windows 11 VM. Shipped at /usr/bin/enable-vfio.sh.
#
# WHY NOT vfio-pci.ids=?  The 4TB and 2TB drives are both Crucial T700s and
# share one vendor:device ID. An ids= karg binds BOTH controllers to vfio-pci,
# including the one the OS boots from. We therefore bind by PCI ADDRESS with a
# driver_override udev rule that is included in the initramfs.
#
# Prereqs (in the image): kargs amd_iommu=on iommu=pt (recipe-desktop.yml).
#
# Usage: sudo enable-vfio.sh [PCI-ADDRESS]     e.g. sudo enable-vfio.sh 0000:02:00.0
#        sudo enable-vfio.sh --remove
set -euo pipefail
[[ $EUID -eq 0 ]] || { echo "ERROR: run with sudo" >&2; exit 1; }

RULE=/etc/udev/rules.d/10-vfio-nvme.rules
MODPROBE=/etc/modprobe.d/vfio-nvme.conf

if [[ "${1:-}" == "--remove" ]]; then
    rm -f "$RULE" "$MODPROBE"
    rpm-ostree initramfs --disable 2>/dev/null || true
    echo "Removed. Reboot to return the controller to the nvme driver."
    exit 0
fi

echo "=== NVMe controllers ==="
ROOT_SRC=$(findmnt -no SOURCE / | sed 's/\[.*\]//')
ROOT_DISK=$(lsblk -no PKNAME "$ROOT_SRC" | head -1); ROOT_DISK=${ROOT_DISK:-?}
for ctrl in /sys/class/nvme/nvme*; do
    addr=$(basename "$(readlink -f "$ctrl/device")")
    disks=$(ls "$ctrl" | grep -E '^nvme[0-9]+n[0-9]+$' | tr '\n' ' ')
    model=$(cat "$ctrl/model" 2>/dev/null | xargs)
    mark=""; for d in $disks; do [[ "$ROOT_DISK" == "$d"* || "$ROOT_DISK" == "$d" ]] && mark="  <-- OS DISK, do not pass through"; done
    printf '  %s  %-24s %s%s\n' "$addr" "$model" "$disks" "$mark"
done

ADDR="${1:-}"
if [[ -z "$ADDR" ]]; then
    read -rp "PCI address of the controller to pass through (e.g. 0000:02:00.0): " ADDR
fi
[[ "$ADDR" =~ ^[0-9a-f]{4}:[0-9a-f]{2}:[0-9a-f]{2}\.[0-9]$ ]] || { echo "ERROR: bad address format, want 0000:02:00.0" >&2; exit 1; }
[[ -e "/sys/bus/pci/devices/$ADDR" ]] || { echo "ERROR: no device at $ADDR" >&2; exit 1; }

# Refuse the controller that holds /
for ctrl in /sys/class/nvme/nvme*; do
    if [[ $(basename "$(readlink -f "$ctrl/device")") == "$ADDR" ]]; then
        for d in $(ls "$ctrl" | grep -E '^nvme[0-9]+n[0-9]+$'); do
            [[ "$ROOT_DISK" == "$d"* ]] && { echo "ERROR: $ADDR holds the root filesystem — refusing" >&2; exit 1; }
        done
    fi
done

echo ""
echo "Binding $ADDR to vfio-pci at boot via driver_override"
cat > "$RULE" <<EOF
# Generated by enable-vfio.sh — bind ONE NVMe controller (by address) to vfio-pci.
ACTION=="add", SUBSYSTEM=="pci", KERNELS=="$ADDR", ATTR{driver_override}="vfio-pci"
EOF
cat > "$MODPROBE" <<'EOF'
# Load vfio-pci before nvme so the driver_override above wins the race.
softdep nvme pre: vfio-pci
EOF

# Ship both into the initramfs (rpm-ostree builds it locally from now on).
rpm-ostree initramfs --enable \
    --arg=-I --arg="$RULE" \
    --arg=-I --arg="$MODPROBE" \
    --arg=--add-drivers --arg="vfio-pci vfio vfio_iommu_type1"

group=$(basename "$(readlink -f "/sys/bus/pci/devices/$ADDR/iommu_group")" 2>/dev/null || echo "?")
echo ""
echo "IOMMU group of $ADDR: $group  (everything in that group goes to the VM together):"
ls "/sys/kernel/iommu_groups/$group/devices" 2>/dev/null | sed 's/^/  /'
echo ""
echo "REBOOT, then verify:  lspci -nnk -s $ADDR      (Kernel driver in use: vfio-pci)"
echo "Then in virt-manager: Add Hardware -> PCI Host Device -> $ADDR"
