# Kickstart for frmwrk (Framework 13 AMD) — spec L1, docs/install.md.
#
# Use with the STOCK Fedora COSMIC Atomic 44 ISO. At the boot menu press e and add:
#   inst.ks=https://raw.githubusercontent.com/samwick07/fedora-cosmic-bluebuild/main/install/frmwrk.ks
#   cosmic.disk=<the target's name in /dev/disk/by-id>     (required; nothing else is touched)
#   cosmic.hostname=frmwrk-test                             (optional; default frmwrk)
#
# Declared here: the partitioning on that one disk, the image, the hostname.
# Typed in the installer: the LUKS passphrase (asked once for both volumes), the user.
# Secrets never go in this public file. The image finishes the rest at first boot
# (signed origin, hibernation kernel arguments).

graphical

# Partitioning, generated by %pre for the disk named on the boot line.
%include /tmp/cosmic-disk.ks

# The image itself, straight from the registry. The origin starts unverified (the
# installer has no key for it); cosmic-signed-origin.service moves it to
# ostree-image-signed at first boot, so every later update is verified.
ostreecontainer --url=ghcr.io/samwick07/fedora-cosmic-frmwrk:latest --transport=registry --no-signature-verification

bootloader --timeout=3 --append="rhgb quiet"
rootpw --lock
firstboot --disable

%pre --interpreter=/usr/bin/bash --erroronfail --log=/tmp/cosmic-pre.log
set -euo pipefail
CMDLINE="${COSMIC_CMDLINE:-/proc/cmdline}"
BYID="${COSMIC_BYID:-/dev/disk/by-id}"
arg() { tr ' ' '\n' < "$CMDLINE" | sed -n "s/^$1=//p" | tail -1; }
die() { echo "cosmic.ks: $*" | tee /dev/tty1 >&2 || true; exit 1; }

DISK=$(arg cosmic.disk)
HOST=$(arg cosmic.hostname); HOST=${HOST:-frmwrk}
[[ -n "$DISK" ]] || die "add cosmic.disk=<name in /dev/disk/by-id> to the boot line (see the top of the kickstart)"
[[ "$DISK" != */* ]] || die "cosmic.disk takes a name in /dev/disk/by-id, not a path"
DEV=$(readlink -f "$BYID/$DISK" || true)
[[ -n "$DEV" && -b "$DEV" ]] || die "no disk /dev/disk/by-id/$DISK"

# Never install over the Workstation's 4TB or the DAS: refuse a disk holding a LUKS volume
# whose UUID hashes to one of these (sha256 of the protected UUIDs; site.env, private).
PROTECTED="c7f127450550b31a8cd697825358fb3b41bfea8f5c5a02b93cafc90bec5b3117 1678e66df006144c2cc3bdc8fd5562a1ad608600d2bdb67d0aa830e99d373d57 8eb37c8f09c463e8ced2dbd535cd1b76726ef283f615224811df38f12cfe5410"
while read -r part; do
    uuid=$(blkid -s UUID -o value "$part" 2>/dev/null || true)
    [[ "$(blkid -s TYPE -o value "$part" 2>/dev/null || true)" == crypto_LUKS && -n "$uuid" ]] || continue
    h=$(printf %s "$uuid" | sha256sum | cut -c1-64)
    [[ " $PROTECTED " != *" $h "* ]] || die "REFUSED: $DISK holds a protected LUKS volume (Workstation or DAS)"
done < <(lsblk -lnpo NAME "$DEV")

# Swap must hold all of RAM for hibernation (spec F2): 96 GiB, or RAM if larger.
RAM_MB=$(awk '/MemTotal/ {print int($2/1024)+1}' /proc/meminfo)
SWAP_MB=98304; (( RAM_MB > SWAP_MB )) && SWAP_MB=$RAM_MB

D="disk/by-id/$DISK"
cat > /tmp/cosmic-disk.ks <<EOT
ignoredisk --only-use=$D
clearpart --all --initlabel --disklabel=gpt --drives=$D
part /boot/efi --fstype=efi --size=1024 --ondisk=$D
part /boot --fstype=ext4 --size=2048 --ondisk=$D
part swap --size=$SWAP_MB --encrypted --luks-version=luks2 --ondisk=$D
part btrfs.01 --size=20480 --grow --encrypted --luks-version=luks2 --ondisk=$D
btrfs none --label=fedora btrfs.01
btrfs / --subvol --name=root LABEL=fedora
btrfs /home --subvol --name=home LABEL=fedora
network --hostname=$HOST
EOT
echo "cosmic.ks: installing to $DISK ($DEV, $(lsblk -dno SIZE,MODEL "$DEV")) as $HOST, swap $SWAP_MB MiB"
%end
