name: bluebuild

on:
  schedule:
    - cron: "00 17 * * *"  # build at 17:00 UTC every day
  push:
    paths-ignore:
      - "**.md"
  pull_request:
  workflow_dispatch:  # allow manual triggering

concurrency:
  # only run one build at a time
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  bluebuild:
    name: Build Custom Image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    strategy:
      fail-fast: false  # don't cancel desktop build if framework build fails
      matrix:
        recipe:
          - recipe-framework.yml
          - recipe-desktop.yml

    steps:
      - name: Build Custom Image
        uses: blue-build/github-action@v1.13
        with:
          recipe: ${{ matrix.recipe }}
          cosign_private_key: ${{ secrets.SIGNING_SECRET }}
          registry_token: ${{ github.token }}
          pr_event_number: ${{ github.event.number }}
          maximize_build_space: true
